---
- name: Install & start service
  hosts: all
  become: yes
  vars:
  - app: httpd
  tasks:
  - name: Install httpd
    yum: 
      name: "{{ app }}"
      state: present
    tags: i-httpd
  - name: start httpd service
    service: 
      name: "{{ app }}"
      state: started
      enabled: true
    tags: ss-httpd   